### ISSUE TITLE
Crash when starting game

### ISSUE THREAD

**Issue by Collecter128** [Zoko061602/Polymancy#5]
I had a lot of mods installed when this happened so I have no clue which one did this but I will upload the crash report so maybe it can help.

[crash-2020-09-29_15.30.22-client.txt](https://github.com/Zoko061602/Polymancy/files/5301748/crash-2020-09-29_15.30.22-client.txt)

**Comment by Zokonius** [comment]
Looks like you are using an outdated version of Embers, try using Embers Rekindled instead.

**Comment by Collecter128** [comment]
Okay thanks.
